bitcoin:
  testnet:
      TESTNET: True
      ADDRTYPE_P2PKH: 111
      ADDRTYPE_P2SH: 196
      ADDRTYPE_P2WPKH: 3
      XPRV_HEADER: 0x04358394
      XPUB_HEADER: 0x043587cf
      HEADERS_URL: "https://headers.electrum.org/testnet_headers"
      GENESIS: "000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943"
  nolnet:
      NOLNET: True
      TESTNET: True
      ADDRTYPE_P2PKH: 0
      ADDRTYPE_P2SH: 5
      ADDRTYPE_P2WPKH: 6
      XPRV_HEADER: 0x0488ade4
      XPUB_HEADER: 0x0488b21e
      HEADERS_URL: "https://headers.electrum.org/nolnet_headers"
      GENESIS: "663c88be18d07c45f87f910b93a1a71ed9ef1946cad50eb6a6f3af4c424625c6"
  net:
      TESTNET: False
      NOLNET: False
      ADDRTYPE_P2PKH: 0
      ADDRTYPE_P2SH: 5
      ADDRTYPE_P2WPKH: 6
      XPRV_HEADER: 0x0488ade4
      XPUB_HEADER: 0x0488b21e
      HEADERS_URL: "https://headers.electrum.org/blockchain_headers"
      GENESIS: "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"

sibcoin:
  testnet:
      TESTNET: True
      ADDRTYPE_P2PKH: 111
      ADDRTYPE_P2SH: 1964
      ADDRTYPE_P2WPKH: 3
      XPRV_HEADER: 0x04358394
      XPUB_HEADER: 0x043587cf
      HEADERS_URL: "https://headers.electrum.org/testnet_headers"
      GENESIS: "000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943"
  nolnet:
      NOLNET: True
      TESTNET: True
      ADDRTYPE_P2PKH: 0
      ADDRTYPE_P2SH: 5
      ADDRTYPE_P2WPKH: 6
      XPRV_HEADER: 0x0488ade4
      XPUB_HEADER: 0x0488b21e
      HEADERS_URL: "https://headers.electrum.org/nolnet_headers"
      GENESIS: "663c88be18d07c45f87f910b93a1a71ed9ef1946cad50eb6a6f3af4c424625c6"
  net:
      TESTNET: False
      NOLNET: False
      ADDRTYPE_P2PKH: 0x3F
      ADDRTYPE_P2SH: 0x80
      ADDRTYPE_P2WPKH: 0x28
      XPRV_HEADER: 0x0488b21e
      XPUB_HEADER: 0x0488ade4
      HEADERS_URL: "https://headers.electrum.org/blockchain_headers"
      GENESIS: "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"

translate:
  crowdin_identifier: sibcoinelectrum